-- cleanup.sql
-- Clean up all demo objects for Caller's Rights vs Owner's Rights Demo

USE ROLE ACCOUNTADMIN;

-- Drop agent
DROP AGENT IF EXISTS DEV_DB.PUBLIC.RIGHTS_TEST_AGENT;

-- Drop V2 procedures (owned by TEST_ROLE)
DROP PROCEDURE IF EXISTS DEV_DB.PUBLIC.UPDATE_TABLE_CALLER_RIGHTS_V2(STRING, INT, FLOAT);
DROP PROCEDURE IF EXISTS DEV_DB.PUBLIC.UPDATE_TABLE_OWNER_RIGHTS_V2(STRING, INT, FLOAT);

-- Drop original procedures (owned by ACCOUNTADMIN) if they exist
DROP PROCEDURE IF EXISTS DEV_DB.PUBLIC.UPDATE_TABLE_CALLER_RIGHTS(STRING, INT, FLOAT);
DROP PROCEDURE IF EXISTS DEV_DB.PUBLIC.UPDATE_TABLE_OWNER_RIGHTS(STRING, INT, FLOAT);

-- Drop databases
DROP DATABASE IF EXISTS DEV_DB;
DROP DATABASE IF EXISTS PROD_DB;

-- Drop roles
DROP ROLE IF EXISTS TEST_ROLE;
DROP ROLE IF EXISTS TEST_ROLE_DEV_ONLY;

SELECT 'Cleanup complete - all demo objects removed' as STATUS;
